# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
    # Schedule updates (each hour)
    schedule: [{ cron: '0 * * * *' }]
    # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
    push: { branches: ['master', 'main'] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  # Your GitHub token
                  # The following scopes are required:
                  #  - public_access (default scope)
                  # The following additional scopes may be required:
                  #  - read:org      (for organization related metrics)
                  #  - read:user     (for user related data)
                  #  - read:packages (for some packages related data)
                  #  - repo          (optional, if you want to include private repositories)
                  token: ${{ secrets.METRICS_TOKEN }}

                  # Options
                  user: lifeng-87
                  template: classic
                  base: header, activity, community, repositories, metadata
                  config_timezone: Asia/Taipei
                  plugin_anilist: yes
                  plugin_anilist_limit: 2
                  plugin_anilist_limit_characters: 22
                  plugin_anilist_medias: anime
                  plugin_anilist_sections: favorites, characters
                  plugin_anilist_shuffle: yes
                  plugin_anilist_user: lifeng87
                  plugin_habits: no
                  plugin_habits_charts_type: classic
                  plugin_habits_days: 14
                  plugin_habits_facts: yes
                  plugin_habits_charts: yes
                  plugin_habits_from: 200
                  plugin_languages: no
                  plugin_languages_analysis_timeout: 15
                  plugin_languages_categories: markup, programming
                  plugin_languages_colors: github
                  plugin_languages_limit: 8
                  plugin_languages_recent_categories: markup, programming
                  plugin_languages_recent_days: 14
                  plugin_languages_recent_load: 300
                  plugin_languages_sections: most-used
                  plugin_languages_threshold: 0%
                  plugin_tweets: yes
                  plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
                  plugin_tweets_attachments: yes
                  plugin_tweets_limit: 1
                  plugin_tweets_user: lifeng87
                  plugin_wakatime: no
                  plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
                  plugin_wakatime_days: 30
                  plugin_wakatime_languages_other: yes
                  plugin_wakatime_limit: 8
                  plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
                  plugin_wakatime_url: https://wakatime.com
                  plugin_wakatime_user: lifeng87
